#####################################################################
## author      : liam                                              ##
## date-time   : 28/10/2012                                         ##
#####################################################################



#all: clean build

build:
#$(CC) $(SRC) -o $(TARGET)
	gcc -pthread sempipetest.c -o sempipetest
